// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: FirebaseOptionsProd.currentPlatform,
/// );
/// ```
class FirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_WEB',
    appId: '1:595210992630:web:dcc09f0bbbe465dc9565d7',
    messagingSenderId: '595210992630',
    projectId: 'mintizy-prod',
    authDomain: 'mintizy-prod.firebaseapp.com',
    storageBucket: 'mintizy-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_ANDROID',
    appId: '1:595210992630:android:a22d1650b8d473ea9565d7',
    messagingSenderId: '595210992630',
    projectId: 'mintizy-prod',
    storageBucket: 'mintizy-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_IOS',
    appId: '1:595210992630:ios:376e311136b122799565d7',
    messagingSenderId: '595210992630',
    projectId: 'mintizy-prod',
    storageBucket: 'mintizy-prod.appspot.com',
    iosClientId:
        '595210992630-k1qjnvl7itmint0oebn6a3bmfrlpt6q4.apps.googleusercontent.com',
    iosBundleId: 'com.mds.digital_project',
  );
}
