// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: FirebaseOptionsDev.currentPlatform,
/// );
/// ```
class FirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtERMOOeJ9dn7GS35ec7cLxuGprhRivug',
    appId: '1:541380443715:web:f684700ff5c851c762def6',
    messagingSenderId: '541380443715',
    projectId: 'mintizy-app',
    authDomain: 'mintizy-app.firebaseapp.com',
    storageBucket: 'mintizy-app.appspot.com',
    measurementId: 'G-0VZRD2EM8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADR5ThqJELxolLfGuxWbg29RHJMHj366Q',
    appId: '1:541380443715:android:4c3e200568f98d6062def6',
    messagingSenderId: '541380443715',
    projectId: 'mintizy-app',
    storageBucket: 'mintizy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI771PtQF2MsiFcjMEUwrDP7ygddc7Xxs',
    appId: '1:541380443715:ios:f1f1345c2b2525d762def6',
    messagingSenderId: '541380443715',
    projectId: 'mintizy-app',
    storageBucket: 'mintizy-app.appspot.com',
    iosClientId:
        '541380443715-f97tpncs7mfr76b8vvaeal2mgu02f42g.apps.googleusercontent.com',
    iosBundleId: 'com.mds.digital_project',
  );
}
